title : GitHub Pages + Jekyll Tutorial
description : This is a tutorial page for making a simple Website by using GitHub Pages and Jekyll

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
repository: UI-FASILKOM-OS/extra182

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github:
  zip_url: https://github.com/UI-FASILKOM-OS/extra182/zipball/master
  tar_url: https://github.com/UI-FASILKOM-OS/extra182/tarball/master

encoding: UTF-8
timezone: Asia/Jakarta
show_downloads: true
share: true
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Analytics
#google_analytics: UA-89852122-1

plugins:
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-github-metadata

# CAN CHANGE
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# gfm_quirks: paragraph_end
# CAN NOT CHANGE
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
